SUPABASE_URL = "https://hyndhledwvknysnzrfta.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5bmRobGVkd3ZrbnlzbnpyZnRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDg1MzgsImV4cCI6MjA1OTkyNDUzOH0.nhCpRAKa8PG91clhrBlKdl79yw13ec0mjq_MS_0F0SI"
UPLOAD_PASSWORD = "saito0120"
LARK_APP_ID = "cli_a82d43e951f99010"
LARK_APP_SECRET = "r6qalZMW2YUDdM8F0C6BPfE1grKWytPv"
LARK_SPREADSHEET_TOKEN = "O6VQsoFDOhOPV7t3qSslkoSEg3b"
LARK_SHEET_ID = "91fd41"
